name: "\U0001F41E Bug report"
description: Create a bug report to help us improve this package
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please carefully read the contribution docs before creating a bug report
        👉 https://github.com/poppinss/.github/blob/main/docs/CONTRIBUTING.md#reporting-bugs

  - type: input
    id: package-version
    attributes:
      label: Package version
      description: You can run `npm info <pkg-name> --depth=0` to check the package version
      placeholder: Package version
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction-repo
    attributes:
      label: Reproduction repo
      description: Link to the Reproduction repo that we can use to reproduce the issue
      placeholder: Optional, but recommended
    validations:
      required: false